### PR TITLE
adaptation to autolayout

### PR DESCRIPTION
**Pull request by kos9kus**
handle an orientation of device
## and needed protocol for own animation of constraints of view 

func collapsedChangedForNewRect(NewRect: CGRect) {
        self.view.layoutIfNeeded()
        self.constrantOfDropDownView.constant = NewRect.size.height;
        UIView.animateWithDuration(0.5, delay: 0, options: .TransitionCrossDissolve, animations: {
            self.view.layoutIfNeeded()

```
        }, completion: nil)

}
```

---

### CODE REVIEW

**Comment by davecom** [comment]
Thanks for the contribution.  Why did you remove the animation?  How does this deal with autolayout?

**Comment by kos9kus** [comment]
no big deal
but it doesn't affect on an animation of constraint ( I mean an contemporary autolayout ) it's currenlty surplus animation.
i decide you should implement a library with  support autolayout and the library should implement autolayout itself 
becouse now the view don't work with some constraints 
regards

**Comment by davecom** [comment]
I don't understand completely what you're saying.  But, if you want to make suggestions about how to support auto-layout from within the confines of the project, I'm open to it.  The way I'm implementing it in my own project is doing manipulations from the delegate method collapsedChanged().  The delegate has a reference to the DKDropMenu so it can query it for frame information.

**Comment by kos9kus** [comment]
Well, I get frame information and  after assign the value to constraint.constant then  I should do make animation of my changing constraint again within delegate method? Right?
Animation of view inside of your class and custom animation will execute simultaneously,
My take on it, Animation block inside of DKDropMenu doesn't make sense 
Do you agree with me?

**Comment by davecom** [comment]
I think you're probably right. I'll need to think about it a bit.  Even better would be to make the component work well with auto-layout from the start, but I'm not sure what I need to do for that.

**Comment by kos9kus** [comment]
Yes, The component from the start would be perfectly.
If i will find time and make it in the future, I will make a pull request right away.

**Comment by rsdev-darshan** [comment]
it works great!! but i want a drop menu for the View that is placed in the navigation title... any idea how can that be achieved?

**Comment by davecom** [comment]
@rsdev-darshan You could possibly set this to the navigationItem.titleView - let me know how it goes.  I haven't tried it myself.

**Pull request closed without merging**
